"""role

Revision ID: 2df34023f2d2
Revises: 4898839fc808
Create Date: 2023-12-18 19:05:44.849478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2df34023f2d2"
down_revision: Union[str, None] = "4898839fc808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role as ENUM('admin', 'moderator', 'user')")
    op.add_column(
        "users",
        sa.Column(
            "role", sa.Enum("admin", "moderator", "user", name="role"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
